#ifndef GPIO_DRIVER_H  // Prevents multiple inclusion of this header file
#define GPIO_DRIVER_H

#include "sdkconfig.h"          // ESP-IDF configuration header (auto-generated by menuconfig)
#include <stdio.h>              // Standard I/O functions (e.g., printf)
#include "freertos/FreeRTOS.h"  // FreeRTOS core functions and types
#include "freertos/task.h"      // FreeRTOS task management functions
#include "driver/gpio.h"       // GPIO driver functions and types
#include "esp_rom_sys.h"      // ESP ROM functions (e.g., delay)
#include "config.h"           // Project-specific configuration (e.g., GPIO pins)


#define LED_PIN1   GPIO_NUM_4  // LED connected to GPIO4
#define LED_PIN2   GPIO_NUM_5  // LED connected to GPIO5
#define BUTTON_PIN GPIO_NUM_37 // Button connected to GPIO37 (input with pull-up)

/*
 * Function: gpio_led_blink
 * Blinks the specified LED using delay-based toggling.
 * led: GPIO pin number of LED
 */
void gpio_led_blink(gpio_num_t led);
/*
 * Function: gpio_led_polling
 * Blinks the specified LED using FreeRTOS delay for non-blocking behavior.
 * led: GPIO pin number of LED
 */
void gpio_led_polling(gpio_num_t led);
/*
 * Function: gpio_button_polling
 * Polls the button state and controls the LED accordingly.
 * led   : GPIO pin number of LED
 * button: GPIO pin number of button
 */
void gpio_button_polling(gpio_num_t led, gpio_num_t button);
/*
 * Function: gpio_button_interrupt_init
 * Initializes the button as an interrupt source.
 * led   : GPIO pin number of LED
 * button: GPIO pin number of button
 */

void gpio_button_interrupt_init(gpio_num_t led, gpio_num_t button);

/*
 * Function: led_task1
 * FreeRTOS task for LED control (Task 1).
 */
void led_task1(void *pvParameters);

/*
 * Function: led_task2
 * FreeRTOS task for LED control (Task 2).
 */
void led_task2(void *pvParameters);

/*
 * Function: led_task_with_param
 * FreeRTOS task that controls LED using parameters passed at runtime.
 * pvParameters: pointer to configuration or GPIO pin
 */
void led_task_with_param(void *pvParameters);
#endif // GPIO_DRIVER_H