#ifndef UART_DRIVER_H            // Prevents multiple inclusion of this header file
#define UART_DRIVER_H

#include <stdint.h>             // Standard integer types (e.g., uint8_t)
#include <stdio.h>              // Standard I/O functions (e.g., printf)
#include<string.h>              // String manipulation functions (e.g., strlen, strcmp)
#include "freertos/FreeRTOS.h"  // FreeRTOS core functions and types
#include "freertos/task.h"      // FreeRTOS task management functions
#include "driver/uart.h"        // UART driver functions and types
#include "driver/gpio.h"        // GPIO driver functions and types
#include "esp_log.h"           // ESP-IDF logging functions  
#include "sdkconfig.h"         // ESP-IDF configuration header (auto-generated by menuconfig)
#include "config.h"            // Project-specific configuration (e.g., GPIO pins, UART settings)
#include "gpio_driver.h"       // GPIO control functions (for LED control in command mode)

#define UART_PORT UART_NUM_1    // UART port number
#define UART_TX_PIN 43          // UART TX pin (GPIO43)
#define UART_RX_PIN 44          // UART RX pin (GPIO44)
#define UART_BAUD_RATE 115200   // UART baud rate

/*
 * Function: led_init
 * Initializes GPIO for LED control.
 * Used when UART commands control LED behavior.
 */
void led_init(void);

/*
 * Function: uart_init
 * Initializes UART with configured parameters:
 * - Baud rate
 * - TX/RX pins
 * - Data format
 */
void uart_init(void);

/*
 * Function: transmit_string
 * Sends a null-terminated string over UART.
 *
 * data: pointer to string to be transmitted
 */
void transmit_string(const char *data);

/*
 * Function: receive_string
 * FreeRTOS task that continuously receives data from UART.
 * Can be used for command parsing (e.g., LED ON/OFF).
 * arg: optional parameter (unused or configuration pointer)
 */
void receive_string(void *arg);

#endif // UART_DRIVER_H
